config/routes.rb
MyLastWord::Application.routes.draw do
  resources :parametres


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => "public#index"

  get '/verification/:token', to: 'validation#verify', as: 'verify'

  namespace :home do
    root :to => 'account#index'
    resources :contacts
    resources :messages
    get '/parameters', to: 'parametres#edit', as: 'parameters'
    post '/parameters', to: 'parametres#update', as: 'parameters'
    get '/profile', to: 'users#edit', as: 'edit_user'
    put '/profile', to: 'users#update'
  end

 # devise_for :admin_users, ActiveAdmin::devise.config
  ActiveAdmin.routes(self)

  match '/auth/:provider/callback' => 'authentications#create'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_and_belongs_to_many :messages

  belongs_to :user
  attr_accessible :mail, :nom, :prenom, :user_id

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  telephone_regex = /\\d+/i
  validates :nom ,:presence => true     ,
            :length   => { :maximum => 50 }              ;
  validates :prenom ,:presence => true               ;
  validates :mail ,:presence => true    ,
            :format   => { :with => email_regex }


  def getNomCompletEtAdresse
    return prenom + " "+nom+" ("+mail+")"
  end
end

app/controllers/home/account_controller.rb
class Home::AccountController < ApplicationController

  before_filter :require_authentication
  layout 'home'


  def index
    # Used as homepage for the administration of the website.
  end


  protected

  def require_authentication
    unless current_user
      render :file   => 'views/forbidden.html.erb',
             :layout => 'error',
             :status => 403
      return
    end
  end

end
 

app/controllers/home/contacts_controller.rb
class Home::ContactsController < Home::AccountController
  # GET /tweets
  # GET /tweets.json
  layout 'home'

  def index
    @title = t('site.home.contact.title')
    @contacts = current_user.contacts

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacts }
    end
  end

  # GET /tweets/new
  # GET /tweets/new.json
  def new
    @title = t('site.home.contact.ajouter')
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @contact = Contact.new(params[:contact])
    @contact.user = current_user
    respond_to do |format|
      if @contact.save
        format.html { redirect_to home_contacts_path, notice: 'Le contact a ete ajoute a votre carnet' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact }
    end
  end


  # PUT /tweets/1
  # PUT /tweets/1.json
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to home_contacts_path, notice: 'Le contact a ete mis a jour.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    redirect_to home_contacts_path
  end


  def edit
    @title = t('site.home.contact.modifier')
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end


  private
  def authenticate
    deny_access unless signed_in?
  end


end

app/controllers/home/messages_controller.rb
class Home::MessagesController  < Home::AccountController


  layout 'home'
  def index
    @title = t('site.home.message.title')
    @messages = current_user.messages

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end


  # GET /tweets/new
  # GET /tweets/new.json
  def new
    @title = t('site.home.message.creer')
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end


  def edit
    @title = t('site.home.message.modifier')
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @message = Message.new(params[:message])
    @message.user = current_user
    respond_to do |format|
      if @message.save
        format.html { redirect_to home_messages_path, notice: 'Le message a ete ajoute a votre carnet' }
        format.json { render json: @message, status: :created, location:  @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end


  # PUT /tweets/1
  # PUT /tweets/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to home_messages_path, notice: 'Le contact a ete mis a jour.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    redirect_to home_messages_path
  end



end

app/controllers/home/parametres_controller.rb
class Home::ParametresController < Home::AccountController

  layout 'home'
  include ParametresHelper

  def edit
    @title = t('site.home.parametres.titre')
    @date = date_prochain_rappel (current_user.dateDerniereValidation)
    @user = current_user;
  end

  def update

    respond_to do |format|
      if current_user.update_attributes(params[:user])
        @user = current_user
        @date = date_prochain_rappel (current_user.dateDerniereValidation)
        format.html { render :partial => "form", :object => @user, notice: 'Le contact a ete mis a jour.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


end

app/controllers/home/users_controller.rb
# administration/registrations_controller.rb
class Home::UsersController < Home::AccountController


  layout 'home'
  def edit
    @titre = "Edition profil"
    @user = current_user
  end

  def update
    if current_user.update_attributes(params[:user])
      flash[:success] = "Profil actualise."
      redirect_to home_root_path
    else
      flash[:fail] = "Impossible de mettre a jour le profil."
      redirect_to home_edit_user_path
    end
  end

end

app/views/home/contacts/_form.html.erb
<%= simple_form_for [:home, @contact] do |f| %>
    <% if @contact.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@contact.errors.count, "error") %> empêche l'enregistrement du contact:</h2>

          <ul>
            <% @contact.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :prenom %><br />
      <%= f.text_field :prenom %>
    </div>
    <div class="field">
      <%= f.label :nom %><br />
      <%= f.text_field :nom %>
    </div>
    <div class="field">
      <%= f.label :mail %><br />
      <%= f.text_field :mail %>
    </div>


    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/home/contacts/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', home_contacts_path %>

app/views/home/contacts/index.html.erb
<p class="intro">
  <%= t 'site.home.contact.intro', :nb => pluralize(@contacts.size, 'contact') %>
</p>

<table class="table table-hover">
  <thead>
      <tr>
        <th>Prenom</th>
        <th>Nom</th>
        <th>E-mail</th>
        <th></th>
      </tr>
  </thead>

  <% @contacts.each do |contact| %>
      <tr url="<%= edit_home_contact_path(contact) %>" onmouseover="$('.delete<%= contact.id %>').css('visibility','visible');" onmouseout="$('.delete<%= contact.id %>').css('visibility','hidden');" style = "cursor: pointer">
        <td><%= contact.prenom %></td>
        <td><%= contact.nom %></td>
        <td><%= contact.mail %></td>
        <td><%= button_to '', home_contact_path(contact), :method => :delete, :class => "icone delete delete#{contact.id}", :title => 'Test',data: { confirm: 'Are you sure?' },:style=> "visibility : hidden" %></td>

      </tr>
  <% end %>
</table>



<div class="actions">
  <%= link_to "Ajouter un contact", new_home_contact_path, :class => "blue_button" %>
</div>


app/views/home/contacts/new.html.erb
<%= render 'form' %>

<%= link_to 'Retour à la liste des contacts', home_contacts_path %>