config/routes.rb
MyLastWord::Application.routes.draw do
  resources :parametres


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => "public#index"

  get '/verification/:token', to: 'validation#verify', as: 'verify'

  namespace :home do
    root :to => 'account#index'
    resources :contacts
    resources :messages
    get '/parameters', to: 'parametres#edit', as: 'parameters'
    post '/parameters', to: 'parametres#update', as: 'parameters'
    get '/profile', to: 'users#edit', as: 'edit_user'
    put '/profile', to: 'users#update'
  end

 # devise_for :admin_users, ActiveAdmin::devise.config
  ActiveAdmin.routes(self)

  match '/auth/:provider/callback' => 'authentications#create'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t("site.title") %></title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= csrf_meta_tag %>
  <!-- Styles -->
  <%= stylesheet_link_tag "bootstrap.min", :media => "all" %>
  <%= stylesheet_link_tag "bootstrap-responsive.min", :media => "all" %>
  <%= stylesheet_link_tag "bootstrap-overrides", :media => "all" %>
  <%= stylesheet_link_tag "theme", :media => "all" %>
  <%= stylesheet_link_tag "index", :media => "screen" %>
  <%= stylesheet_link_tag "public", :media => "all" %>

  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag "lib/animate", :media => "all" %>

  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body class="pull_top">
<div class="navbar navbar-inverse navbar-static-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="index.html">
        <strong><%= t("site.title") %></strong>
      </a>
      <div class="nav-collapse collapse">
        <ul class="nav pull-right">
          <li><a href="/" class="active"><%= t("site.public.menu.home") %></a></li>
          <li><a href="about-us.html"><%= t("site.public.menu.aboutus") %></a></li>
          <li><a href="contact.html"><%= t("site.public.menu.contact") %></a></li>
          <li><%= link_to t("site.public.menu.signin"), new_user_session_path, :class => "btn-header" %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<%= yield %>

<!-- starts footer -->
<footer id="footer">
  <div class="container">
    <div class="row info">
      <div class="span6 residence">
        <ul>
          <li>2301 East Lamar Blvd. Suite 140. City, Arlington.</li>
          <li>United States, Zip Code TX 76006.</li>
        </ul>
      </div>
      <div class="span5 touch">
        <ul>
          <li><strong>P.</strong> 1 817 274 2933</li>
          <li><strong>E.</strong><a href="#"> bootstrap@twitter.com</a></li>
        </ul>
      </div>
    </div>
    <div class="row credits">
      <div class="span12">
        <div class="row social">
          <div class="span12">
            <a href="#" class="facebook">
              <span class="socialicons ico1"></span>
              <span class="socialicons_h ico1h"></span>
            </a>
            <a href="#" class="twitter">
              <span class="socialicons ico2"></span>
              <span class="socialicons_h ico2h"></span>
            </a>
            <a href="#" class="gplus">
              <span class="socialicons ico3"></span>
              <span class="socialicons_h ico3h"></span>
            </a>
            <a href="#" class="flickr">
              <span class="socialicons ico4"></span>
              <span class="socialicons_h ico4h"></span>
            </a>
            <a href="#" class="pinterest">
              <span class="socialicons ico5"></span>
              <span class="socialicons_h ico5h"></span>
            </a>
            <a href="#" class="dribble">
              <span class="socialicons ico6"></span>
              <span class="socialicons_h ico6h"></span>
            </a>
            <a href="#" class="behance">
              <span class="socialicons ico7"></span>
              <span class="socialicons_h ico7h"></span>
            </a>
          </div>
        </div>
        <div class="row copyright">
          <div class="span12">
            © 2013 Clean Canvas. All rights reserved. Theme by Detail Canvas.
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

<!-- Scripts -->
<script src="http://code.jquery.com/jquery-latest.js"></script>
<%= javascript_include_tag "bootstrap.min" %>
<%= javascript_include_tag "theme" %>
<%= javascript_include_tag "index-slider" %>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t("site.title") %></title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= javascript_include_tag "application" %>

  <!-- Styles -->
  <%= stylesheet_link_tag "bootstrap.min", :media => "all" %>
  <%= stylesheet_link_tag "bootstrap-responsive.min", :media => "all" %>
  <%= stylesheet_link_tag "bootstrap-overrides", :media => "all" %>
  <%= stylesheet_link_tag "theme", :media => "all" %>
  <%= stylesheet_link_tag "index", :media => "screen" %>
  <%= stylesheet_link_tag "public", :media => "all" %>
  <%= stylesheet_link_tag "ui-lightness/jquery-ui.min", :media => "all" %>

  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag "lib/animate", :media => "all" %>

  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body class="pull_top">
<div class="navbar navbar-inverse navbar-static-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/home">
        <strong><%= t("site.title") %></strong>
      </a>
      <div class="nav-collapse collapse">
        <ul class="nav pull-right">
          <li><%= link_to "Profil", home_edit_user_path %></li>
          <li><%= link_to "Se deconnecter", destroy_user_session_path, :method => :delete %></li>


          <% if current_user.has_role?(:admin) %>
              <li><%= link_to "Administration", admin_root_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div id="homeyield" style="min-height: 500px">
  <div class="container">
    <div class="row-fluid">
      <div class="span4">
        <div class="well sidebar-nav">
          <ul class="nav nav-list">
            <li class="nav-header"><%= t('site.home.menu.title') %></li>
            <li><%= link_to t('site.home.menu.parametres'), home_parameters_path %></li>
            <li><%= link_to t('site.home.menu.contacts'), home_contacts_path  %></li>
            <li><%= link_to t('site.home.menu.messages'), home_messages_path  %></li>
          </ul>
        </div><!--/.well -->
      </div><!--/span-->
      <div class="span8">

        <div class="section_header">
          <h3><%= @title %> </h3>
        </div>
        <%= bootstrap_flash %>
        <% flash.each do |key, value| %>
            <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </div>
    </div><!--/row-->
  </div>
</div>

<!-- starts footer -->
<footer id="footer">
  <div class="container">
    <div class="row info">
      <div class="span6 residence">
        <ul>
          <li>2301 East Lamar Blvd. Suite 140. City, Arlington.</li>
          <li>United States, Zip Code TX 76006.</li>
        </ul>
      </div>
      <div class="span5 touch">
        <ul>
          <li><strong>P.</strong> 1 817 274 2933</li>
          <li><strong>E.</strong><a href="#"> bootstrap@twitter.com</a></li>
        </ul>
      </div>
    </div>
    <div class="row credits">
      <div class="span12">
        <div class="row social">
          <div class="span12">
            <a href="#" class="facebook">
              <span class="socialicons ico1"></span>
              <span class="socialicons_h ico1h"></span>
            </a>
            <a href="#" class="twitter">
              <span class="socialicons ico2"></span>
              <span class="socialicons_h ico2h"></span>
            </a>
            <a href="#" class="gplus">
              <span class="socialicons ico3"></span>
              <span class="socialicons_h ico3h"></span>
            </a>
            <a href="#" class="flickr">
              <span class="socialicons ico4"></span>
              <span class="socialicons_h ico4h"></span>
            </a>
            <a href="#" class="pinterest">
              <span class="socialicons ico5"></span>
              <span class="socialicons_h ico5h"></span>
            </a>
            <a href="#" class="dribble">
              <span class="socialicons ico6"></span>
              <span class="socialicons_h ico6h"></span>
            </a>
            <a href="#" class="behance">
              <span class="socialicons ico7"></span>
              <span class="socialicons_h ico7h"></span>
            </a>
          </div>
        </div>
        <div class="row copyright">
          <div class="span12">
            © 2013 Clean Canvas. All rights reserved. Theme by Detail Canvas.
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

<!-- Scripts -->
<script src="http://code.jquery.com/jquery-latest.js"></script>
<%= javascript_include_tag "bootstrap.min" %>
<%= javascript_include_tag "theme" %>
<%= javascript_include_tag "index-slider" %>
<%= javascript_include_tag "jquery-ui.min" %>

</body>
</html>

